#!/usr/bin/env node
// Turn a CSV of directory entries into a plain-SQL dump you can import into your
// deployed app's managed database (Database tab → Import).
//
//   node scripts/csv-to-dump.js data/sample-import.csv > my-directory.sql
//
// The CSV needs a header row with these columns (extra columns are ignored):
//   name,tagline,description,url,category,pricing,tags
// `tags` is optional and pipe-separated, e.g.  cli|open-source|git
//
// The generated SQL is safe to import more than once: it creates the table if
// needed and upserts on `slug`, so it never aborts on a duplicate. That matters
// because the import restores all-or-nothing (ON_ERROR_STOP=1), one duplicate
// key without the upsert would roll the whole import back.

const fs = require("fs");

function fail(msg) {
  process.stderr.write(msg + "\n");
  process.exit(1);
}

// Minimal RFC-4180-ish CSV parser: handles quoted fields, embedded commas,
// escaped quotes ("") and both \n and \r\n line endings.
function parseCSV(text) {
  const rows = [];
  let row = [];
  let field = "";
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        field += c;
      }
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ",") {
      row.push(field);
      field = "";
    } else if (c === "\n") {
      row.push(field);
      rows.push(row);
      row = [];
      field = "";
    } else if (c === "\r") {
      // ignore; the \n handles the row break
    } else {
      field += c;
    }
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  return rows.filter((r) => r.length > 1 || (r.length === 1 && r[0].trim() !== ""));
}

function slugify(name) {
  return String(name)
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

// SQL string literal, double any single quotes.
function lit(value) {
  return "'" + String(value == null ? "" : value).replace(/'/g, "''") + "'";
}

function tagArray(raw) {
  const tags = String(raw || "")
    .split(/[|;]/)
    .map((t) => t.trim())
    .filter(Boolean);
  if (tags.length === 0) return "'{}'";
  return "ARRAY[" + tags.map(lit).join(", ") + "]::text[]";
}

const inputPath = process.argv[2];
if (!inputPath) fail("usage: node scripts/csv-to-dump.js <input.csv> > out.sql");

const text = fs.readFileSync(inputPath, "utf8");
const rows = parseCSV(text);
if (rows.length < 2) fail("CSV has no data rows (need a header row + at least one entry).");

const header = rows[0].map((h) => h.trim().toLowerCase());
const col = (name) => header.indexOf(name);
const iName = col("name");
if (iName === -1) fail('CSV must have a "name" column.');
const iTagline = col("tagline");
const iDesc = col("description");
const iUrl = col("url");
const iCategory = col("category");
const iPricing = col("pricing");
const iTags = col("tags");

const out = [];
out.push("-- Directory import generated by scripts/csv-to-dump.js");
out.push("-- Import this file from your app's Database tab → Import.");
out.push("");
out.push(`CREATE TABLE IF NOT EXISTS entries (
  id          SERIAL PRIMARY KEY,
  slug        TEXT UNIQUE NOT NULL,
  name        TEXT NOT NULL,
  tagline     TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  url         TEXT NOT NULL DEFAULT '',
  category    TEXT NOT NULL DEFAULT 'Uncategorized',
  pricing     TEXT NOT NULL DEFAULT '',
  tags        TEXT[] NOT NULL DEFAULT '{}',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);`);
out.push("");

const seen = new Set();
let count = 0;
for (let r = 1; r < rows.length; r++) {
  const row = rows[r];
  const name = (row[iName] || "").trim();
  if (!name) continue;
  let slug = slugify(name);
  if (!slug) continue;
  // De-dupe slugs within the same file so the upsert targets are unique.
  let unique = slug;
  let n = 2;
  while (seen.has(unique)) unique = `${slug}-${n++}`;
  seen.add(unique);

  const values = [
    lit(unique),
    lit(name),
    lit(iTagline > -1 ? row[iTagline] : ""),
    lit(iDesc > -1 ? row[iDesc] : ""),
    lit(iUrl > -1 ? row[iUrl] : ""),
    lit(iCategory > -1 && row[iCategory] ? row[iCategory] : "Uncategorized"),
    lit(iPricing > -1 ? row[iPricing] : ""),
    tagArray(iTags > -1 ? row[iTags] : ""),
  ].join(", ");

  out.push(
    `INSERT INTO entries (slug, name, tagline, description, url, category, pricing, tags)
VALUES (${values})
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, tagline = EXCLUDED.tagline, description = EXCLUDED.description,
  url = EXCLUDED.url, category = EXCLUDED.category, pricing = EXCLUDED.pricing, tags = EXCLUDED.tags;`
  );
  count++;
}

process.stderr.write(`wrote ${count} entries to SQL\n`);
process.stdout.write(out.join("\n") + "\n");
